name: Build

on:
  push:
    branches:
      - master

jobs:
  canaryBuild:
    name: Canary Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[S]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Gradle Build
        run: |
          ./gradlew assembleAfatDebug
          echo ::set-env name=APK_FILE::$(find TMessagesProj/build/outputs/apk -name "*.apk")
      - uses: actions/upload-artifact@v1
        with:
          name: TMessagesProj
          path: ${{ env.APK_FILE }}